# Generated by Django 4.0.2 on 2022-03-08 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_name', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=999, primary_key=True, serialize=False)),
                ('task_notes', models.CharField(max_length=999)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('worked_hours', models.IntegerField()),
                ('estimated_hours', models.IntegerField()),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('complexity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana.assignee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana.project')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asana.sprint')),
            ],
        ),
    ]
