# Generated by Django 4.0.2 on 2022-04-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=999, serialize=False)),
                ('notes', models.CharField(max_length=999)),
                ('assignee', models.CharField(max_length=999)),
                ('project', models.CharField(max_length=999)),
                ('sprint', models.CharField(max_length=999)),
                ('start_date', models.DateField(default=None, null=True)),
                ('end_date', models.DateField(default=None, null=True)),
                ('worked_hours', models.IntegerField(default=None, null=True)),
                ('estimated_hours', models.IntegerField(default=None, null=True)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=None, max_length=1, null=True)),
                ('complexity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default=None, max_length=1, null=True)),
            ],
        ),
    ]
