# Generated by Django 4.0.2 on 2022-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(default='TASK NAME', max_length=999, primary_key=True, serialize=False),
        ),
    ]
